// GENERATED by tool/gen_warmup_glyphs.dart — do not edit.
// Re-run after editing app_en.arb / app_zh.arb:
//   dart run tool/gen_warmup_glyphs.dart
//
// Every unique glyph across the l10n bundles. [UiInteractiveWarmup] shapes
// these at startup so the first CJK text render does not pay the
// one-time Noto Sans SC shaping cost on the UI thread.

/// 643 unique glyphs from app_en.arb + app_zh.arb.
const warmupGlyphs = ' !"#\$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~·×–—“”…↑→↓、。「」一三上下不与且两个中串为主久义之也了二于些交亮人仅仍从仓他代令以件任份会传位住体作你使例供侧便保信修值做停储像允先光克入全公兰关其具典内册再写冲准凑凭出击分切列则刚创删别到制刷前剪副功加务动劫化匹区单危即历原参及发取变叠口另只可台史右号各合同名后向否吧启告员命和商器回团固图在地址均型域基堆填境墨处备复外多大天失夹始子字存它安完定实容宽密对导射将小少尔尚就局屏展属工左已布常并序库应底度建开弃式强当录径待得心必志快忽性恢息成我或户所手才打执扫找把折报拆拉拖拨择括持指按换据捷授排接控推描提插搜摘撤操支收改放效数整文断新方无日时映是显景智暂暗更替最有服期未本机权束条松板构析林果某查标栈栏树校格框案桌检森槽模次止正此步每比没法注洁洋活浅测浏海消深混添清源滚激点焦然片版独环现珀理琥生用由界留略登白的盖盘目直相看知石码确磁示离私称移程空突窗立端符第等筛签简管箱类粘系索紧紫约级纹线组细终经绑结给络统继绪续维缓编缩缺网罗置者而聊聚背能脚自致航色芯若获菜落藏行表被装要覆见观规视览解言认议记许设访证识词试话该语误请读调象败贴起距跟跨路跳踪身轮载辑输边迁过运近返还这进远连退送适选通速道部配释里重量钟钥钮链销错键镜长闭问闲间队限除险隆随隐需靠面页顶项须预频题颜验高默（），：；？';

