// GENERATED by tool/gen_warmup_glyphs.dart — do not edit.
// Re-run after editing app_en.arb / app_zh.arb:
//   dart run tool/gen_warmup_glyphs.dart
//
// Every unique glyph across the l10n bundles. [UiInteractiveWarmup] shapes
// these at startup so the first CJK text render does not pay the
// one-time Noto Sans SC shaping cost on the UI thread.

/// 642 unique glyphs from app_en.arb + app_zh.arb.
const warmupGlyphs = ' !"#\$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~·×–—“”…↑→↓、。「」一三上下不与专且两个中串为主久么义之也了二于些交亮人什仅今仍从仓他代令以件任份会传位住体作你使例供侧便保信修值做停储允先光克入全兰关其具典内再写冲准凑凭出击分切列则刚创删别到制刷前剪副功加务动劫包化匹区单危即历原参及发取变叠口另只可台史右各合同名后向否吧启告员命和商器回团固图在地均型域基堆填境墨处备复外多大天失夹如始子字存它安完定实家容宽密对导射将小少尔尚就局展属工左已布带帮常并序库应底建开弃式引强当录径待得心必志快忽性恢息情想成我或户所手才打执找技把折报拆拉拖择持指按换据捷授排接控推提插搜摘撤操支收改放效数整文断新方旁无日时映是显景智暂暗更替最有服期未本机权束条松板构析林果某查标栈栏树校格框案检森槽模次止正此步每比没法注洁洋活浅测浏海消深混添清源滚激点焦片版牌独环现珀理琥生用由界留略登白的盖盘目直相看知石码确磁示私称移程空突窗立端符第等筛签简管箱类粘系索紧紫级纹线组细终经绑结给统继绪续缓编缩缺网罗置者而聊聚背能脚自致航色芯若获菜落藏行表被装要覆见观规视览解言认议记许设访证识词试话该详语误请读调象败贴起距跟跨路跳踪身轮载辑输边迁过运近返还这进远连退送适选通速部配释里重量钟钥钮链销错键长闭问闲间队附限除险隆随隐需面音页顶项须预题颜风验高麦默（），：；？';

