// GENERATED by tool/gen_warmup_glyphs.dart — do not edit.
// Re-run after editing app_en.arb / app_zh.arb:
//   dart run tool/gen_warmup_glyphs.dart
//
// Every unique glyph across the l10n bundles. [UiInteractiveWarmup] shapes
// these at startup so the first CJK text render does not pay the
// one-time Noto Sans SC shaping cost on the UI thread.

/// 804 unique glyphs from app_en.arb + app_zh.arb.
const warmupGlyphs = ' !"#\$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~·×–—“”…↑→↓−≥①②③✨、。「」一三上下不与专且丢两个中串为主久么义之也了事二于五些交产享亮亲人什仅今仍从仓他代令以们件任份休优会传但位低住体作你使例供依侧便保信修值假做停储允元先克入全公六兰共关其具典内册再写冲况准凑凭出击分切划列则刚创删别到制刷刺前剪副力功加务动助劫包化匹区协单占卡危即却卸历压厘原参及友发取受变叠口另只召可台史右号各合同名后向否吧含启告员周命和响哪唤唯商器四回因团围固图在地场址均块型域基堆塞填境增墨处备复外多大天失夸夹奖如始委子字存它安完官定实审家容宽密对导射将小少尔尚就局层展属工左己已布带帮常平并广序库应底度建开弃式引强归当录形影往径待得循心必忆志快忽态怎思性总恢息情想意成我或户所手才打托执扩扫找承技把抓折护报拆拉拖择持挂指按挑换据捷授排探接控推描提插搜摘撤操支收改放效数整文断新方施旁无日旧早时明星映是显景晰智暂暗更替最有服期未本机杂权束条来松板极构析林果查标栈栏树校核格框案桌档检森植概模次止正此步段每比求汇沙沟没沿法泛注洁洋活派浅测浏海消涉深混添清源滑滚滤激点焦然片版牌状独环现珀理琥生用由界留略登白的盖盘目直相省看知石码研础确磁示禁离私种称移程稍稿空突窗立端符第等筛签简算管箱类粘系索紧紫约级纹线组细终经绑结给络绝统继绪续维缓编缘缩缺网罗置考者而聊职联聚能脚自至致航色节芯花若范草荐获菜落藏行表被装要覆见观规视览角解言计认让议记许论设访证识词试话询该详语误说请读调谱象负责败账贴资赖起跑距跟跨路跳踪身转轮载辑输边达迁过运近返还这进远连述退送适选逗通速遵邀部都配释里重量钟钥钩钮链销错键长闭问闲间阅队阶阻附际限除险隆随隐隔需非面音页顶项顺须预领题额风首验骤高麦默（），：；？';

