// ignore_for_file: avoid_print
//
// Generates the built-in terminal theme catalog from cmux's theme reference
// doc. Run from `client/`:
//
//   dart run tool/gen_terminal_themes.dart [path-to-09-themes.md]
//
// Input defaults to D:/git/cmux-windows/docs/analysis/09-themes.md. Output is
// lib/theme/terminal/terminal_theme_catalog.g.dart, a `const` list of
// CmuxTerminalTheme — no JSON asset, zero runtime parse cost. Regenerating is
// idempotent (byte-identical), so the file is checked in. Fails loudly if the
// doc does not yield exactly 23 themes (12 dark + 11 light) with 16 ANSI
// colours each.

import 'dart:io';

import 'package:teampilot/theme/terminal/cmux_theme_markdown_parser.dart';

const _defaultInput = 'D:/git/cmux-windows/docs/analysis/09-themes.md';
const _outputFile = 'lib/theme/terminal/terminal_theme_catalog.g.dart';

void main(List<String> args) {
  final inputPath = args.isNotEmpty ? args.first : _defaultInput;
  final file = File(inputPath);
  if (!file.existsSync()) {
    stderr.writeln('Missing themes doc: $inputPath');
    exit(1);
  }

  final List<CmuxThemeSpec> specs;
  try {
    specs = parseCmuxThemesMarkdown(file.readAsStringSync());
    validateCmuxThemeCatalog(specs);
  } on FormatException catch (e) {
    stderr.writeln('Failed to parse $inputPath: ${e.message}');
    exit(1);
  }

  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/gen_terminal_themes.dart — do not edit.')
    ..writeln('// Source: $_defaultInput')
    ..writeln('// Re-run: dart run tool/gen_terminal_themes.dart')
    ..writeln('//')
    ..writeln(
      '// ${specs.length} built-in terminal themes ported from cmux '
      '(TerminalThemes.cs).',
    )
    ..writeln()
    ..writeln("import 'package:flutter/painting.dart';")
    ..writeln()
    ..writeln("import 'cmux_terminal_theme.dart';")
    ..writeln()
    ..writeln('/// The 23 built-in terminal themes (12 dark, then 11 light).')
    ..writeln('const List<CmuxTerminalTheme> kCmuxTerminalThemes = [');
  for (final spec in specs) {
    _writeTheme(buffer, spec);
  }
  buffer
    ..writeln('];')
    ..writeln()
    ..writeln('final Map<String, CmuxTerminalTheme> _kThemesById = {')
    ..writeln('  for (final theme in kCmuxTerminalThemes) theme.id: theme,')
    ..writeln('};')
    ..writeln()
    ..writeln('/// Looks up a built-in theme by its stable [CmuxTerminalTheme.id].')
    ..writeln('CmuxTerminalTheme? cmuxTerminalThemeById(String id) =>')
    ..writeln('    _kThemesById[id];');

  File(_outputFile).writeAsStringSync(buffer.toString());
  print('Wrote $_outputFile (${specs.length} themes).');
}

void _writeTheme(StringBuffer buffer, CmuxThemeSpec spec) {
  buffer
    ..writeln('  CmuxTerminalTheme(')
    ..writeln("    name: '${spec.name}',")
    ..writeln("    author: '${_escape(spec.author)}',")
    ..writeln('    isDark: ${spec.isDark},')
    ..writeln('    background: ${_color(spec.background)},')
    ..writeln('    foreground: ${_color(spec.foreground)},')
    ..writeln('    cursor: ${_color(spec.cursor)},')
    ..writeln('    selection: ${_color(spec.selection)},')
    ..writeln('    searchHit: ${_color(spec.searchHit)},')
    ..writeln('    searchHitCurrent: ${_color(spec.searchHitCurrent)},')
    ..writeln('    searchHitFg: ${_color(spec.searchHitFg)},')
    ..writeln(
      '    accent: ${spec.accent == null ? 'null' : _color(spec.accent!)},',
    )
    ..writeln('    ansi: [')
    ..writeln('      ${spec.ansi.map(_color).join(', ')},')
    ..writeln('    ],')
    ..writeln('  ),');
}

String _color(int rgb) {
  final hex = (0xFF000000 | rgb).toRadixString(16).toUpperCase().padLeft(8, '0');
  return 'Color(0x$hex)';
}

String _escape(String value) => value.replaceAll(r'\', r'\\').replaceAll("'", r"\'");
